#index:
#    path: /
#    controller: App\Controller\DefaultController::index
GatherData:
  path:       /gather
  controller: App\Controller\DataCollectorController::gatherQueueOrganizer
  methods:    GET

ParseData:
  path:       /parse
  controller: App\Controller\DataParserController::parsingQueueOrganizer
  methods:    GET

GetSearchParams:
  path:       /search_params/{id}
  controller: App\Controller\SearchParamsController::getSearchParams
  methods:    GET

GetSearchParamsAll:
  path:       /search_params
  controller: App\Controller\SearchParamsController::getAll
  methods:    GET

CreateSearchParams:
  path:       /search_params
  controller: App\Controller\SearchParamsController::create
  methods:    POST

UpdateSearchParams:
  path:       /search_params/{id}
  controller: App\Controller\SearchParamsController::update
  methods:    PUT
  requirements:
    id: '\d+'

DeleteSearchParams:
  path:       /search_params/{id}
  controller: App\Controller\SearchParamsController::delete
  methods:    DELETE
  requirements:
    id: '\d+'

GetRawData:
  path:       /raw_data/{id}
  controller: App\Controller\RawDataController::getRawData
  methods:    GET

GetRawDataAll:
  path:       /raw_data
  controller: App\Controller\RawDataController::getAll
  methods:    GET

GetOfferData:
  path:       /offer_data/{id}
  controller: App\Controller\OfferDataController::getOfferData
  methods:    GET

GetOfferDataAll:
  path:       /offer_data
  controller: App\Controller\OfferDataController::getAll
  methods:    GET

GetFullOfferInfo:
  path:       /result_data/{id}
  controller: App\Controller\ResultDataController::getFullOfferInfo
  methods:    GET

GetFullOfferInfoAll:
  path:       /result_data
  controller: App\Controller\ResultDataController::getFullOfferInfoAll
  methods:    GET